service: lambda-invoke

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: "*"
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

custom:
  serverless-offline:

functions:
  hello:
    events:
      - http:
          method: any
          path: /handler
    handler: handler.handle
